<?php

/**
 * @file
 * Demonstrates how to show and and hide inputs with the #state attribute.
 *
 * Great documentation here:
 * http://api.drupal.org/api/drupal/includes--common.inc/function/drupal_process_states/7
 * Includes list of possible states.
 */

/**
 * Implements hook_menu().
 */
function beauty10ajaxloop_menu() {
  $items['beauty/beauty10ajaxloop'] = array(
    'title' => 'Adding inputs with the #ajax attribute',
    'page callback' => 'beauty10ajaxloop_page',
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Returns form render array.
 */
function beauty10ajaxloop_form($form, &$form_state) {
  
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your full name, please'),
  );
  $form['email'] = array(
    '#title' => t('Email'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your e-mail address.'),
  );


  // Looping version for infinite accounts.
  $more_accounts = TRUE;
  $i = 1;
  
  while ($more_accounts == TRUE) {
    $form['subaccount_'. $i] = array(
      '#type' => 'fieldset',
      '#title' => 'Sub account '. $i,
      '#suffix' => '<div id="subaccount_' . ($i + 1) . '_wrapper"></div>',
    );
    $form['subaccount_' . $i]['subaccount_' . $i . '_name'] = array(
      '#title' => t('Name'),
      '#type' => 'textfield',
      '#ajax' => array(
        'callback' => 'beauty10ajaxloop_subaccount_callback',
        'wrapper' => 'subaccount_' . ($i + 1) . '_wrapper',
       ),
    );
    $form['subaccount_' . $i]['subaccount_' . $i . '_email'] = array(
      '#title' => t('Email'),
      '#type' => 'textfield',
    );
    
    if (!isset($form_state['values']) || $form_state['values']['subaccount_' . ($i) . '_name'] == '') {
      $more_accounts = FALSE;
    }
    
    $i++;
  }
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  
  return $form;
}

/**
 * Ajax callback for subaccount input in beauty10ajaxloop_form form.
 */
function beauty10ajaxloop_subaccount_callback($form, $form_state) {
  
  // Loop for infinite inputs
  $more_accounts = TRUE;
  $i = 1;
  
  while ($more_accounts == TRUE) {
    if ($form_state['values']['subaccount_' . ($i) . '_name'] == '') {
      $more_accounts = FALSE;
    }
    $i++;
  }
  
  return $form['subaccount_' . ($i-1)];

}

/**
 * Menu callback.
 */
function beauty10ajaxloop_page() {
  return drupal_get_form('beauty10ajaxloop_form');
}