<?php

/**
 * @file
 * Demonstrates how to use the Uniform libraray and module to stylize inputs
 * consistantly across different browsers.
 *
 * A couple things are required for this to work.
 * 1. Download and install http://drupal.org/project/uniform and http://drupal.org/project/libraries
 * 2. Download the Uniform library http://github.com/pixelmatrix/uniform/archives/master
 * 3. Create /sites/all/libraries folder and extrat Uniform library to /sites/all/libraries/uniform
 *    (Review Uniform module README more for detailed info)
 * 4. Two themes have been added. To add themes, follow the instructions in the Uniform module README.
 */


/**
 * Implements hook_menu().
 */
function beauty13uniform_menu() {
  $items['beauty/beauty13uniform'] = array(
    'title' => 'With Uniform',
    'page callback' => 'beauty13uniform_page',
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Returns form render array.
 */
function beauty13uniform_form($form, &$form_state) {
  
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your full name, please'),
  );
  $form['email'] = array(
    '#title' => t('Email'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your e-mail address.'),
  );
  $form['password'] = array(
    '#title' => t('Password'),
    '#type' => 'password',
    '#required' => TRUE,
    '#description' => t('An amazingly secure password. See <a href="http://xkcd.com/936/">http://xkcd.com/936/</a>.'),
  );
  $form['file'] = array(
    '#title' => t('File'),
    '#type' => 'file',
    '#description' => t('A file input.'),
  );
  $form['company_count'] = array(
    '#title' => t('Company population'),
    '#type' => 'select',
    '#required' => TRUE,
    '#options' => array(
      'Just 1 guy in an attic',
      '2-10 people in an attic',
      '11-50 people in a hip office space with no practical furniture',
      "More than 50 people and a few we don't remember the names of",
    ),
    '#description' => t('How many people in your company?'),
  );
  $form['company_type'] = array(
    '#title' => t('Company type'),
    '#type' => 'radios',
    '#required' => TRUE,
    '#options' => array(
      'Sole proprietorship',
      'Anarchy and mayhem',
      'Ruled by hamsters',
    ),
    '#description' => t('Please chose the option that best describes your company.'),
  );
  $form['company_values'] = array(
    '#title' => t('Company values'),
    '#type' => 'checkboxes',
    '#required' => TRUE,
    '#options' => array(
      "Crush the competition, crush our friends, crush our grandmothers if they get in our way!!!",
      "Always give back something. Even if it's a moldy cracker.",
      "Peace and love are our path. And Battlestar Galactica.",
    ),
    '#description' => t('Please choose your values.'),
  );

  $form['explain'] = array(
    '#title' => t('Please explain your what makes you a prime candidate for our beta test'),
    '#type' => 'textarea',
    '#resizable' => TRUE,
    '#description' => t('Beta spaces are limited, but let us know if there is a really good reason to let you in.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Menu callback.
 */
function beauty13uniform_page() {
  return drupal_get_form('beauty13uniform_form');
}