<?php

/**
 * @file
 * Demonstrates how to use transparent inputs.
 */

/**
 * Implements hook_menu().
 */
function beauty05invisible_menu() {
  $items['beauty/beauty05invisible'] = array(
    'title' => 'Adding background and hiding inputs (kind of)',
    'page callback' => 'beauty05invisible_page',
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Returns form render array.
 */
function beauty05invisible_form($form, &$form_state) {
  
  $form['#attached']['css'] = array(
    drupal_get_path('module', 'beauty05invisible') . '/beauty05invisible.less',
  );
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your full name, please'),
  );
  $form['email'] = array(
    '#title' => t('Email'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your e-mail address.'),
  );
  $form['company'] = array(
    '#title' => t('Company Name'),
    '#type' => 'textfield',
    '#description' => t('The company you are associated with, if any.'),
  );
  $form['explain'] = array(
    '#title' => t('Please explain your what makes you a prime candidate for our beta test'),
    '#type' => 'textarea',
    '#resizable' => TRUE,
    '#description' => t('Beta spaces are limited, but let us know if there is a really good reason to let you in.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Menu callback.
 */
function beauty05invisible_page() {
  return drupal_get_form('beauty05invisible_form');
}