<?php

/**
 * @file
 * Demonstrates how to show an input's description only when focused on.
 */


/**
 * Implements hook_menu().
 */
function beauty16hidedescription_menu() {
  $items['beauty/beauty16hidedescription'] = array(
    'title' => 'Show description only when clicking on element',
    'page callback' => 'beauty16hidedescription_page',
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Returns form render array.
 */
function beauty16hidedescription_form($form, &$form_state) {

  $form['#attached']['css'] = array(
    drupal_get_path('module', 'beauty16hidedescription') . '/beauty16hidedescription.less',
  );
  $form['#attached']['js'] = array(
    drupal_get_path('module', 'beauty16hidedescription') . '/beauty16hidedescription.js',
  );
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your full name, please'),
  );
  $form['email'] = array(
    '#title' => t('Email'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Your e-mail address.'),
  );
  $form['company'] = array(
    '#title' => t('Company Name'),
    '#type' => 'textfield',
    '#description' => t('The company you are associated with, if any.'),
  );
  $form['company_type'] = array(
    '#title' => t('Company type'),
    '#type' => 'radios',
    '#required' => TRUE,
    '#options' => array(
      'Sole proprietorship',
      'Anarchy and mayhem',
      'Ruled by hamsters',
    ),
    '#description' => t('Please chose the option that best describes your company.'),
  );
  $form['company_values'] = array(
    '#title' => t('Company values'),
    '#type' => 'checkboxes',
    '#required' => TRUE,
    '#options' => array(
      "Crush the competition, crush our friends, crush our grandmothers if they get in our way!!!",
      "Always give back something. Even if it's a moldy cracker.",
      "Peace and love are our path. And Battlestar Galactica.",
    ),
    '#description' => t('Please choose your values.'),
  );
  $form['explain'] = array(
    '#title' => t('Please explain your what makes you a prime candidate for our beta test'),
    '#type' => 'textarea',
    '#resizable' => TRUE,
    '#description' => t('Beta spaces are limited, but let us know if there is a really good reason to let you in.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Menu callback.
 */
function beauty16hidedescription_page() {
  return drupal_get_form('beauty16hidedescription_form');
}